<?php

namespace app\models;

/**
 * This is the model class for table "item_statuses".
 *
 * @property int $id
 * @property string $text
 * @property string $color
 * @property string $icon
 * @property int $updated
 *
 * @property Items[] $items
 */
class ItemStatuses extends \yii\db\ActiveRecord
{
    const STATUS_NEW = 2;
    const STATUS_OK = 3;
    const STATUS_FAIL = 4;
    const STATUS_OPEN = 5;
    const STATUS_MARK = 6;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'item_statuses';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['text', 'color', 'icon'], 'string'],
            [['updated'], 'integer'],
        ];
    }

    public function beforeSave($insert)
    {
        if (empty($this->updated))
            if ($this->isNewRecord)
                $this->updated = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'text' => 'Text',
            'color' => 'Color',
            'icon' => 'Icon',
            'updated' => 'Updated',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(Items::className(), ['status_id' => 'id']);
    }
}
